// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovdgcmykwmwooslodpjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZGdjbXlrd213b29zbG9kcGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDI0MTksImV4cCI6MjA2NDIxODQxOX0.vxFkKk5VMVL5IYHByD-Zb0g3pripJdrEv1EZioZ0ZEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);